In [4]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({"studentid":list(range(1001,1010)),
                    "age":[24,26,np.nan,"srk",15,18,"20",20.6,"19.4"]})
df

In [ ]:
df["age"].unique().tolist()

In [ ]:
df.columns.tolist()

In [ ]:
#observe the wrong data

l=[]
for i in df["age"].unique().tolist():
    if type(i) not in [int, float]:
        l.append(i)
print(l)

In [ ]:
#filter/select the wrong data

df[df["age"].isin(l)]

**treat the wrong data**

In [ ]:
df.drop(index=df[df["age"].isin(l)].index.tolist())

**replace**

1. replace with original value by contacting backend team (best option)

In [ ]:
#df.iloc[index]  = new values

df.iloc[[3,6,8],1] = [25,26,27]

2. replace with statistical value(mean for numeric, mode for categorical)

In [ ]:
df.iloc[[3,6,8],1] = df["age"].mean()

# Duplicates

In [ ]:
df = pd.DataFrame({"studentid":[101,102,102,103,104],
                    "age":[24,27,27,28,29]})
df

In [ ]:
#observe the duplicates

df.duplicated().sum()

In [ ]:
#filter the duplicates

df[df.duplicated()]

In [ ]:
# treat the duplicates

df = df.drop_duplicates()

In [ ]:
df

In [ ]:
df = pd.DataFrame({"studentid":[101,102,102,103,104],
                    "age":[24,27,28,28,29]})
df

In [ ]:
df["studentid"].duplicated().sum()

In [ ]:
df[df["studentid"].duplicated()]

In [ ]:
df[df["studentid"]==102]

In [ ]:
df.drop(index=1)

# Missing values

In [ ]:
df = pd.DataFrame({"studentid":[101,102,np.nan,104,105],
                    "age":[24,27,np.nan,28,np.nan]})
df

In [ ]:
#observe the missing values

df.isnull()

In [ ]:
#to observe no.of missing values in each column
df.isnull().sum()

In [ ]:
#to observe % of missing values in each column
df.isnull().sum()/df.shape[0]*100

In [ ]:
#to observe no.of missing values in each row
df.isnull().sum(axis=1)

In [ ]:
#to observe % of missing values in each row
df.isnull().sum(axis=1)/df.shape[1]*100

In [ ]:
# filter/extract the missing values
df[df["age"].isnull()]

**treat missing values**

1. Drop/Remove the missing values

In [ ]:
df.drop(index= df[df["age"].isnull()].index)

In [ ]:
df.dropna()

if original data is available : replace with original data

elif % of missing values is <5%  ---> drop the records

elif % of missing values is >30%  ---> drop the column

else, replace statistically

In [ ]:
df["age"] = df["age"].fillna(20)

In [ ]:
df

# Unimportant columns

- drop the column, which has all values as unique values (ex: s.no,roll no, id, pan)
- drop the column, which has all values are same (ex: country : india)
- drop the column, which has missing values >30%

In [ ]:
df = df.drop(columns=[ ,  , , ])

# Outliers

**how to observe the outliers**

In [5]:
df = pd.DataFrame({"X":[1,26,5,10,15,20,18,14,19,24,30,36,22,27,100,150]})
df

      X
0     1
1    26
2     5
3    10
4    15
5    20
6    18
7    14
8    19
9    24
10   30
11   36
12   22
13   27
14  100
15  150

In [15]:
Q1 = df["X"].quantile(0.25)

Q3 = df["X"].quantile(0.75)

IQR = Q3-Q1

ll = Q1-(1.5*IQR)
print("Lower Limit:",ll)

ul = Q3+(1.5*IQR)
print("Upper Limit:",ul)

Lower Limit: -4.75
Upper Limit: 47.25

In [14]:
df["X"].quantile([0,0.25,0.5,0.75,1])

0.00      1.00
0.25     14.75
0.50     21.00
0.75     27.75
1.00    150.00
Name: X, dtype: float64

**extract outliers**

In [16]:
df[(df["X"]<ll) | (df["X"]>ul)]

      X
14  100
15  150

In [18]:
df[(df["X"]<ll) | (df["X"]>ul)].shape[0]

2

- if outlier is wrong data, treat wrong data

        - replace with original data  (1st priority)
        - replace statically

- if outlier is correct data,

        - remove
        - retrain

In [23]:
df.iloc[[14,15],0] = [10,15]

In [24]:
df

     X
0    1
1   26
2    5
3   10
4   15
5   20
6   18
7   14
8   19
9   24
10  30
11  36
12  22
13  27
14  10
15  15

# Data Cleaning

- no fixed code

- data cleaning is dependent on business problem & logical thinking